let stockProductos = [
  {
    id: 1,
    nombre: "Semipermanente pies",
    tipo: "pies",
    cantidad: 1,
    desc: "Lo mejor para tus pies",
    precio: 600,
    wapp: "https://wa.me/93521559",
    img: "../img/semiPies.jpg",
  },
  {
    id: 2,
    nombre: "Semiperm. y Pedicure",
    tipo: "pies",
    cantidad: 1,
    desc: "Lo mejor para tus pies",
    precio: 850,
    wapp: "https://wa.me/93521559",
    img: "../img/pedicureYSemi.jpeg",
  },
  {
    id: 3,
    nombre: "Pedicure esm. tradicional",
    tipo: "pies",
    cantidad: 1,
    desc: "Lo mejor para tus pies",
    precio: 600,
    wapp: "https://wa.me/93521559",
    img: "../img/pedicureEsmTradicional.jpeg",
  },
  {
    id: 4,
    nombre: "Pedicure sin esmaltado",
    tipo: "pies",
    cantidad: 1,
    desc: "Lo mejor para tus pies",
    precio: 500,
    wapp: "https://wa.me/93521559",
    img: "../img/pies.jpg",
  },
  {
    id: 5,
    nombre: "Semipermanente manos",
    tipo: "manos",
    cantidad: 1,
    desc: "Lo mejor para tus manos",
    precio: 600,
    wapp: "https://wa.me/93521559",
    img: "../img/semiManos.jpeg",
  },
  {
    id: 6,
    nombre: "Kaping y Semiperm.",
    tipo: "manos",
    cantidad: 1,
    desc: "Lo mejor para tus manos",
    precio: 850,
    wapp: "https://wa.me/93521559",
    img: "../img/semiYKapi.jpeg",
  },
  {
    id: 7,
    nombre: "Manicure esm. tradicional",
    tipo: "manos",
    cantidad: 1,
    desc: "Lo mejor para tus manos",
    precio: 350,
    wapp: "https://wa.me/93521559",
    img: "../img/manicureEsmTradicional.jpeg",
  },
];
